jobs:
  build:
    name: Build MQTT Paho Java on JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }} ${{ matrix.os }}
      uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Package with Maven skip tests
      run: mvn -B package --file pom.xml -DskipTests
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8.0.192
        os:
        - ubuntu-latest
      max-parallel: 4
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___main.yaml
